	.align 2
voicegroup274::
	voice_keysplit voicegroup005, KeySplitTable1        @ piano
    voice_keysplit voicegroup005, KeySplitTable1        @ piano
    voice_keysplit voicegroup005, KeySplitTable1        @ piano
    voice_keysplit voicegroup005, KeySplitTable1        @ piano
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 128, 204, 51, 242
    voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 128, 204, 51, 242
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 216, 90, 242
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0         @ dulcimer missing
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 248
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 248
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 165, 180, 165
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 165, 206, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149
    voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 99
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 99
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115
    voice_keysplit voicegroup006, KeySplitTable2            @ violin
    voice_keysplit voicegroup006, KeySplitTable2            @ viola
    voice_keysplit voicegroup006, KeySplitTable2            @ cello
    voice_keysplit voicegroup006, KeySplitTable2            @ contrabass
    voice_keysplit voicegroup006, KeySplitTable2            @ tremolo strings
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165
    voice_keysplit voicegroup006, KeySplitTable2            @orchestral strings
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 246, 0, 226
	voice_keysplit voicegroup006, KeySplitTable2            @string ensemble
    voice_keysplit voicegroup006, KeySplitTable2            @string ensemble
    voice_keysplit voicegroup006, KeySplitTable2            @synth strings 1
    voice_keysplit voicegroup006, KeySplitTable2            @synth strings 2
    voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0
    voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 128, 165, 128, 204
	voice_directsound 60, 0, DirectSoundWaveData_unused_unknown_male_voice, 128, 165, 128, 188
    voice_directsound_no_resample 64, 80, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242
    voice_keysplit voicegroup007, KeySplitTable5            @ trumpet
    voice_keysplit voicegroup007, KeySplitTable3            @ trombone
    voice_keysplit voicegroup008, KeySplitTable4            @ tuba
    voice_keysplit voicegroup007, KeySplitTable3            @ muted trumpet
    voice_keysplit voicegroup009, KeySplitTable5            @ french horn
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
    voice_keysplit voicegroup009, KeySplitTable5            @ french horn
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204
    voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127
    voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165       @ ocarina
    voice_square_2 60, 0, 3, 0, 1, 7, 1
    voice_programmable_wave_alt 60, 0, ProgrammableWaveData_4, 0, 7, 15, 2
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound_no_resample 64, 79, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188
    voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242
    voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242
    voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242
    voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242
    voice_programmable_wave 60, 0, ProgrammableWaveData_1, 0, 7, 15, 1
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_directsound_no_resample 64, 24, DirectSoundWaveData_dance_drums_ride_bell, 255, 165, 103, 231
    voice_directsound 62, 64, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 0
    voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0
    voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0
    