-- Diagnostic Nuzlocke state reader for the current Modern Emerald build.
-- Load through EmuHawk: Tools -> Lua Console -> Open Script.
--
-- These addresses come from pokeemerald_modern.map and the code generated by
-- devkitARM r62. They are not the eventual Soul Link mailbox ABI.

local IWRAM_DOMAIN = "IWRAM"
local EWRAM_DOMAIN = "EWRAM"
local EWRAM_BASE = 0x02000000
local EWRAM_END = 0x02040000

local SAVE_BLOCK1_PTR = 0x3D5C -- gSaveBlock1Ptr - 0x03000000
local FLAGS_OFFSET = 0x1364
local ENCOUNTER_FLAGS_OFFSET = 0x3D94
local ENCOUNTER_FLAGS_SIZE = 9
local NUZLOCKE_MODE_OFFSET = 0x3D9E
local NUZLOCKE_CLAUSES_OFFSET = 0x3DA1
local NUZLOCKE_OPTIONS_OFFSET = 0x3DA3

local FLAG_ADVENTURE_STARTED = 0x074
local FLAG_SYS_POKEMON_GET = 0x860
local FLAG_IS_CHAMPION = 0x87F

local function bitIsSet(value, bit)
    return math.floor(value / (2 ^ bit)) % 2 == 1
end

local function yesNo(value)
    return value and "yes" or "no"
end

local function readSaveByte(saveBlock1, offset)
    return memory.read_u8(saveBlock1 - EWRAM_BASE + offset, EWRAM_DOMAIN)
end

local function readFlag(saveBlock1, flag)
    local value = readSaveByte(saveBlock1, FLAGS_OFFSET + math.floor(flag / 8))
    return bitIsSet(value, flag % 8)
end

local function readState()
    local saveBlock1 = memory.read_u32_le(SAVE_BLOCK1_PTR, IWRAM_DOMAIN)
    if saveBlock1 < EWRAM_BASE or saveBlock1 >= EWRAM_END then
        return nil, string.format("waiting for SaveBlock1 (pointer=0x%08X)", saveBlock1)
    end

    local modeByte = readSaveByte(saveBlock1, NUZLOCKE_MODE_OFFSET)
    local clausesByte = readSaveByte(saveBlock1, NUZLOCKE_CLAUSES_OFFSET)
    local optionsByte = readSaveByte(saveBlock1, NUZLOCKE_OPTIONS_OFFSET)
    local enabled = bitIsSet(modeByte, 6)
    local hardcore = bitIsSet(modeByte, 7)
    local easy = bitIsSet(optionsByte, 7)

    local mode
    if easy then
        mode = "EASY"
    elseif not enabled then
        mode = "OFF"
    elseif hardcore then
        mode = "HARDCORE"
    else
        mode = "NORMAL"
    end

    local encounterBytes = {}
    local usedEncounterIds = {}
    for byteIndex = 0, ENCOUNTER_FLAGS_SIZE - 1 do
        local value = readSaveByte(saveBlock1, ENCOUNTER_FLAGS_OFFSET + byteIndex)
        encounterBytes[#encounterBytes + 1] = string.format("%02X", value)

        for bit = 0, 7 do
            local encounterId = byteIndex * 8 + bit
            if encounterId < 0x46 and bitIsSet(value, bit) then
                usedEncounterIds[#usedEncounterIds + 1] = tostring(encounterId)
            end
        end
    end

    local pokemonReceived = readFlag(saveBlock1, FLAG_SYS_POKEMON_GET)
    local adventureStarted = readFlag(saveBlock1, FLAG_ADVENTURE_STARTED)
    local champion = readFlag(saveBlock1, FLAG_IS_CHAMPION)
    local active = enabled and pokemonReceived and adventureStarted and not champion

    local state = {
        saveBlock1 = saveBlock1,
        mode = mode,
        active = active,
        speciesClause = bitIsSet(clausesByte, 5),
        shinyClause = bitIsSet(clausesByte, 6),
        nicknaming = bitIsSet(clausesByte, 7),
        deletion = bitIsSet(optionsByte, 0),
        encountersHex = table.concat(encounterBytes, " "),
        usedEncounterIds = #usedEncounterIds == 0 and "none" or table.concat(usedEncounterIds, ","),
    }

    state.signature = table.concat({
        string.format("%08X", state.saveBlock1), state.mode, tostring(state.active),
        tostring(state.speciesClause), tostring(state.shinyClause),
        tostring(state.nicknaming), tostring(state.deletion), state.encountersHex,
    }, "|")
    return state
end

local function printState(state)
    console.log(string.format(
        "[Nuzlocke] mode=%s active=%s speciesClause=%s shinyClause=%s nicknaming=%s fainted=%s",
        state.mode, yesNo(state.active), yesNo(state.speciesClause),
        yesNo(state.shinyClause), yesNo(state.nicknaming),
        state.deletion and "release" or "cemetery"))
    console.log(string.format(
        "[Nuzlocke] saveBlock1=0x%08X encounters=[%s] usedIds=%s",
        state.saveBlock1, state.encountersHex, state.usedEncounterIds))
end

console.log("[Nuzlocke] diagnostic reader started")

local previousSignature = nil
local previousError = nil
while true do
    local ok, state, stateError = pcall(readState)
    if not ok then
        stateError = state
        state = nil
    end

    if state then
        previousError = nil
        if state.signature ~= previousSignature then
            printState(state)
            previousSignature = state.signature
        end
    elseif stateError ~= previousError then
        console.log("[Nuzlocke] " .. tostring(stateError))
        previousError = stateError
        previousSignature = nil
    end

    emu.frameadvance()
end
