#ifndef GUARD_CONSTANTS_POKEMON_SIZE_RECORD_H
#define GUARD_CONSTANTS_POKEMON_SIZE_RECORD_H

#define UNIT_TEXT_LENGTH_SMALL_SINGLE   0
#define UNIT_TEXT_LENGTH_SMALL_PLURAL   1
#define UNIT_TEXT_LENGTH_SMALL_SYMBOL   2
#define UNIT_TEXT_LENGTH_MEDIUM_SINGLE  3
#define UNIT_TEXT_LENGTH_MEDIUM_PLURAL  4
#define UNIT_TEXT_LENGTH_MEDIUM_SYMBOL  5
#define UNIT_TEXT_WEIGHT_SINGLE         6
#define UNIT_TEXT_WEIGHT_PLURAL         7
#define UNIT_TEXT_WEIGHT_SYMBOL         8

#endif // GUARD_CONSTANTS_POKEMON_SIZE_RECORD_H