#ifndef GUARD_SLIDING_PUZZLES_CONSTANTS_H
#define GUARD_SLIDING_PUZZLES_CONSTANTS_H

#define PUZZLE_KABUTO      0
#define PUZZLE_OMANYTE     1
#define PUZZLE_AERODACTYL  2
#define PUZZLE_HO_OH       3
#define PUZZLE_SOLVED      4
#define PUZZLE_COUNT       5

#endif //GUARD_SLIDING_PUZZLES_CONSTANTS_H
