#ifndef GUARD_SLIDING_PUZZLES_CONSTANTS_H
#define GUARD_SLIDING_PUZZLES_CONSTANTS_H

#define SLIDING_PUZZLE_KABUTO      0
#define SLIDING_PUZZLE_OMANYTE     1
#define SLIDING_PUZZLE_AERODACTYL  2
#define SLIDING_PUZZLE_HO_OH       3
#define SLIDING_PUZZLE_SOLVED      4

#define SLIDING_PUZZLE_COUNT       5

#endif // GUARD_SLIDING_PUZZLES_CONSTANTS_H
