gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_Difficulty::
	.string "Aha…\p"
	.string "And… How do you think this\n"
	.string "adventure is going to be?$"

gText_Birch_LockDifficulty::
	.string "If you need to change the Difficulty\n"
	.string "you can open the Options Menu and\l"
	.string "change it from there.\p"
	.string "You can also lock it, if you want.\n"
	.string "Do you want to lock the\l"
	.string "chosen Difficulty?\p"
	.string "This cannot be changed later.$"

gText_Birch_ChallengeEasy::
	.string "Oh, is that so?\p"
    .string "Easy Mode lowers the challenge by\n"
    .string "scaling down enemy and wild Pokémon.\p"
    .string "Your Pokémon also gain 20% more Exp.\p"
    .string "You can change Difficulty anytime\n"
    .string "from the Options Menu, unless you\l"
    .string "choose to lock the Difficulty.\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any Challenge\l"
	.string "in your journey?\p"
	.string "And what's your name?$"

gText_Birch_ChallengeNormal::
	.string "Oh, is that so?\p"
    .string "Normal Mode keeps the same\n"
    .string "difficulty as vanilla Emerald.\p"
    .string "The only changes are to trainer\n"
    .string "teams and rematches, which are\l"
    .string "greatly improved.\p"
    .string "You can change Difficulty anytime\n"
    .string "from the Options Menu, unless you\l"
    .string "choose to lock the Difficulty.\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any Challenge\l"
	.string "in your journey?\p"
	.string "And what's your name?$"

gText_Birch_ChallengeHard::
    .string "Oh, is that so?\p"
    .string "Hard Mode is more challenging than\n"
    .string "Normal Mode.\p"
    .string "It is not meant to replace dedicated\n"
    .string "Difficulty HackROMs, but uses simple\l"
    .string "mechanics to raise the difficulty.\l"
    .string "This Mode includes:\p"
    .string "Pokémon gain only 60% Experience.\p"
    .string "Enemy and wild {PKMN} level scale\n"
    .string "with your Badges.\p"
    .string "All Badge Boosts removed.\p"
	.string "You can't use more than 4 items\n"
	.string "in battle.\p"
    .string "Certain foes get temporal Stat buffs.\p"
    .string "Exp. Share is nerfed.\p"
    .string "Damage taken rises with more Badges.\p"
    .string "All legendaries are banned in the BF.\p"
    .string "You can change Difficulty anytime\n"
    .string "from the Options Menu, unless you\l"
    .string "choose to lock the Difficulty.\p"
    .string "Options exist to unban legendaries\n"
    .string "and restore normal Experience gain.\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any Challenge\l"
	.string "in your journey?\p"
	.string "And what's your name?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "Oh! So you're {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, of course!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of Littleroot.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"
