@ NOTE: The brailleformat macro in this file is leftover from RS.
@       The numbers are simply skipped over. If you'd like to omit
@       this macro you must also stop it from skipping over this
@       section by editing ScrCmd_braillemessage.
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "SWEET SCENT\n"
	.braille "HERE.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "FIRST COMES\n"
	.braille "MAGNEZONE.\n"
	.braille "LAST COMES\n"
	.braille "VIBRAVA.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "IN THIS\n"
	.braille "CAVE WE\n"
	.braille "HAVE\n"
	.braille "LIVED.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "WE OWE ALL\n"
	.braille "TO THE\n"
	.braille "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "BUT, WE\n"
	.braille "SEALED THE\n"
	.braille "POKEMON\n"
	.braille "AWAY.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "WE FEARED IT.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "THOSE WITH\n"
	.braille "COURAGE,\n"
	.braille "THOSE WITH\n"
	.braille "HOPE.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "OPEN A DOOR.\n"
	.braille "AN ETERNAL\n"
	.braille "POKEMON\n"
	.braille "WAITS.$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "LEFT, LEFT,\n"
	.braille "DOWN, DOWN.\n"
	.braille "THEN, USE\n"
	.braille "ROCK SMASH.$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "STAY CLOSE\n"
	.braille "TO THE WALL.\n"
	.braille "RUN AROUND\n"
	.braille "ONE LAP.$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "THOSE WHO\n"
	.braille "INHERIT OUR\n"
	.braille "WILL, SHINE\n"
	.braille "IN THE MIDDLE.$"

Regieleki_Braille_Sapphire:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "GET THE BLUE\n"
	.braille "GEM WHERE IT\n"
	.braille "RAINS. PUT IT\n"
	.braille "IN THE MIDDLE.$"

Regidrago_Braille_Text:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "DOWN, THREE.\n"
	.braille "RIGHT, FIVE.\n"
	.braille "PRESS THE\n"
	.braille "BUTTON.$"

Regigigas_Braille_Text:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "FIVE TITANS\n"
	.braille "DEFEATED.\n"
	.braille "YOU ARE\n"
	.braille "CHAMPION.$"

UnownChamber_Left_Braille_Text:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "LEFT AND RIGHT\n"
	.braille "RIGHT AND LEFT\n"
	.braille "TWO SIDES OF\n"
	.braille "THE SAME COIN.$"

UnownChamber_Mid_Braille_Text:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "CHECK. MIRROR.\n"
	.braille "EIGHT TIMES.\n"
	.braille "IN ORDER.\n"
	.braille "OR START AGAIN$"

UnownChamber_Right_Braille_Text:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "RIGHT AND LEFT\n"
	.braille "LEFT AND RIGHT\n"
	.braille "TWO SIDES OF\n"
	.braille "SAME MIRROR.$"

UnownChamber_Random_Text_1:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "GOLD$"

UnownChamber_Random_Text_2:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "AND SILVER.$"

UnownChamber_Random_Text_3:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "SILVER$"

UnownChamber_Random_Text_4:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "AND GOLD.$"

UnownChamber_Random_Text_5:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "TWENTY$"

UnownChamber_Random_Text_6:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "EIGHT.$"

UnownChamber_Random_Text_7:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "THEY ARE$"

UnownChamber_Random_Text_8:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "WAITING.$"
