AquaHideout_UnusedRubyMap3_MapScripts::
	map_script MAP_SCRIPT_ON_RESUME, EncounterTable
	map_script MAP_SCRIPT_ON_TRANSITION, EncounterTable
	.byte 0

AquaHideout_UnusedRubyMap3_BonslyMunchEvo::
	msgbox AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text, MSGBOX_NPC
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text:
	.string "Have you see those strange moving\n"
	.string "trees? They are a POKéMON named\l"
	.string "SUDOWOODO! Did you know that?\p"
	.string "It's a POKéMON that disguises itself\n"
	.string "as a small tree.\p"
	.string "And there's also BONSLY, which does\n"
	.string "the same… but doesn't look as\l"
	.string "realistic, or so I think.\p"
	.string "Speaking of which, I've seen them evolve\n"
	.string "while trying to imitate other SUDOWOODO.\p"
	.string "Is that how they evolve?\p"
	.string "If I'm not mistaken, MIME JR. also evolve\n"
	.string "IMITATING other POKéMON.\p"
	.string "Very different from my MUNCHLAX, who\n"
	.string "evolved by FRIENDSHIP, don't you think?$"
