#ifndef GUARD_DIFFICULTY_H
#define GUARD_DIFFICULTY_H
//tx_difficulty_challenges

#define TX_RANDOM_CHAOS_MODE 0
#define TX_RANDOM_ENCOUNTER 1
#define TX_RANDOM_ENCOUNTER_SIMILAR 0
#define TX_RANDOM_TYPE 1
#define TX_RANDOM_TYPE_EFFECTIVNESS 1
#define TX_RANDOM_ABILITIES 1
#define TX_RANDOM_MOVES 1
#define TX_RANDOM_TRAINER 1
#define TX_RANDOM_EVOLUTION 1
#define TX_RANDOM_EVOLUTION_METHODE 0


#define TX_RANDOM_OFFSET_TRAINER 51
#define TX_RANDOM_OFFSET_TYPE 31
#define TX_RANDOM_OFFSET_ABILITY 71
#define TX_RANDOM_OFFSET_MOVES 13
#define TX_RANDOM_OFFSET_ENCOUNTER 0
#define TX_RANDOM_OFFSET_EVOLUTION 41

#define TX_CHALLANGE_EVO_LIMIT 0 //0 off, 1 first, 2 none
#define TX_CHALLANGE_PARTY_LIMIT 4
#define TX_CHALLENGE_NUZLOCKE 1
#define TX_CHALLENGE_ITEM_PLAYER 1
#define TX_CHALLENGE_ITEM_TRAINER 1

#endif // GUARD_DIFFICULTY_H