SafariZone_Southeast_MapScripts::
	.byte 0

SafariZone_Southeast_GliscorEvo::
	msgbox SafariZone_Southeast_GliscorEvo_Text, MSGBOX_NPC
	end

SafariZone_Southeast_GliscorEvo_Text:
	.string "I love all JOHTO POKéMON!\p"
	.string "That's why I need to catch\n"
	.string "a GLIGAR. So then I can get\l"
	.string "a GLISCOR! Which is not from\l"
	.string "JOHTO, but it's cool.\p"
	.string "They evolve only at night,\n"
	.string "just like SNEASEL and MURKROW.$"

@ Event scripts for SafariZone_Southeast are in SafariZone_South/scripts.inc
